# feed: /atom.xml
#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: 机遇
name: cwlseu


# Short bio or description (displayed in the header)
brief-intro: research之路其修远兮，我将上下而求索
url: https://www.deepindeed.cn
permalink: /:title

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://cwlseu.github.io/images/myface.jpg
# other links
github_username: cwlseu
email: caowenlong92@gmail.com
zhihu_username: 
linkedIn_username: https://www.linkedin.com/in/cao-wenlong-7b691262/
dribbble_username:

description_footer: 本站记录我视觉之旅的沿途风景！

# Your disqus shortname, entering this will enable commenting on posts
# disqus_shortname: cwlseu
# duoshuo_shortname: deepindeed
livere_shortname: deepindeed
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-86501439-1

baidu_analytics: 
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
